---
- name: Linux Reboot Demo
  hosts: gsdDev
  gather_facts: no
  become: true
 
  tasks:
    - name: Reboot the machine (Wait for 5 min)
      reboot:
        reboot_timeout: 300
  #notify: Reboot host and wait for it to restart
